name: Build ProxLock

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode project contents / schemes
        run: |
          ls -la
          xcodebuild -list -project ProxLock.xcodeproj || true

      - name: Build app without code signing
        run: |
          xcodebuild -project ProxLock.xcodeproj \
            -scheme ProxLock \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProxLock.app
          path: build/Build/Products/Release/ProxLock.app
