name: Build ProxLock

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean build
        run: rm -rf build

      - name: Build app in Debug without code signing
        run: |
          xcodebuild -project ProxLock.xcodeproj \
            -scheme ProxLock \
            -configuration Debug \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_APPINTENTS=NO \
            SWIFT_OPTIMIZATION_LEVEL=-Onone \
            COMPILER_INDEX_STORE_ENABLE=NO

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProxLock.app
          path: build/Build/Products/Debug/ProxLock.app
