- name: Force export of schemes
  run: |
    defaults write com.apple.dt.Xcode IDECustomDerivedDataLocation -string "$(pwd)/build"
    xcodebuild -project ProxLock.xcodeproj -list
    name: Build ProxLock
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build .app
        run: |
          xcodebuild -project ProxLock.xcodeproj -scheme ProxLock -configuration Release -derivedDataPath build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProxLock.app
          path: build/Build/Products/Release/ProxLock.app
